-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Attumen the Huntsman Raid", {
	[29833] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Attumen the Huntsman Raid", {
	[29833] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Hyakiss the Lurker", {
	[29896] = {"blue","orange"},
})

BigWigs:AddSounds("Hyakiss the Lurker", {
})

BigWigs:AddColors("Moroes Raid", {
	[29448] = "red",
	[37023] = "orange",
	[37066] = {"blue","yellow"},
})

BigWigs:AddSounds("Moroes Raid", {
	[29448] = "warning",
	[37023] = "long",
	[37066] = "alert",
})

BigWigs:AddColors("Maiden of Virtue Raid", {
	[29511] = "red",
	[29522] = {"blue","yellow"},
})

BigWigs:AddSounds("Maiden of Virtue Raid", {
	[29511] = "warning",
	[29522] = "alert",
})

BigWigs:AddColors("Romulo & Julianne", {
	[30822] = {"blue","yellow"},
	[30878] = "orange",
	["buff"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Romulo & Julianne", {
	[30878] = "warning",
	["buff"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("The Big Bad Wolf", {
	[30753] = {"blue","yellow"},
})

BigWigs:AddSounds("The Big Bad Wolf", {
	[30753] = "warning",
})

BigWigs:AddColors("The Crone", {
	[32337] = "orange",
	["spawns"] = "yellow",
})

BigWigs:AddSounds("The Crone", {
	[32337] = "info",
})

BigWigs:AddColors("The Curator Raid", {
	[30254] = "red",
	[30403] = "orange",
})

BigWigs:AddSounds("The Curator Raid", {
	[30254] = "warning",
	[30403] = "long",
})

BigWigs:AddColors("Terestian Illhoof", {
	[30065] = {"green","red"},
	[30115] = {"blue","yellow"},
})

BigWigs:AddSounds("Terestian Illhoof", {
	[30065] = {"info","long"},
	[30115] = "warning",
})

BigWigs:AddColors("Shade of Aran", {
	[29973] = "yellow",
	[30004] = {"blue","red","yellow"},
	["adds"] = {"cyan","orange"},
	["blizzard"] = "orange",
	["drink"] = {"cyan","orange"},
})

BigWigs:AddSounds("Shade of Aran", {
	[29973] = "info",
	[30004] = {"long","warning"},
})

BigWigs:AddColors("Netherspite", {
	[37063] = "yellow",
	[38523] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Netherspite", {
	[37063] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Prince Malchezaar", {
	[30843] = {"blue","red"},
	[30852] = "yellow",
	["infernal"] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Prince Malchezaar", {
	[30843] = "warning",
	[30852] = "alarm",
	["infernal"] = {"alert","info"},
})

BigWigs:AddColors("Nightbane Raid", {
	[30129] = "blue",
	[36922] = "red",
	[37098] = "orange",
	["stages"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Nightbane Raid", {
	[30129] = "underyou",
	[36922] = "alert",
	[37098] = "info",
	["stages"] = "long",
})
