-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Rage Winterchill", {
	[31249] = {"blue","red"},
	[31258] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Rage Winterchill", {
	[31249] = "alert",
	[31258] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Anetheron", {
	[31298] = "orange",
	[31299] = {"blue","green","red"},
	[31306] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Anetheron", {
	[31298] = "alert",
	[31299] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Kaz'rogal", {
	[31447] = {"green","yellow"},
})

BigWigs:AddSounds("Kaz'rogal", {
})

BigWigs:AddColors("Azgalor", {
	[31340] = "orange",
	[31344] = "red",
	[31347] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Azgalor", {
	[31340] = "alarm",
	[31347] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("ArchimondeHyjal", {
	[31970] = {"orange","red"},
	[31972] = {"blue","yellow"},
	[32014] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("ArchimondeHyjal", {
	[31972] = "alert",
	[32014] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Hyjal Summit Trash", {
	["waves"] = {"cyan","orange","yellow"},
})

BigWigs:AddSounds("Hyjal Summit Trash", {
})

BigWigs:AddColors("Hydross the Unstable", {
	[38235] = {"blue","yellow"},
	[38246] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["mark"] = "red",
	["stance"] = "red",
})

BigWigs:AddSounds("Hydross the Unstable", {
	["berserk"] = "alarm",
	["mark"] = "alert",
})

BigWigs:AddColors("The Lurker Below", {
	[37478] = "yellow",
	["dive"] = {"cyan","green","orange","yellow"},
	["spout"] = {"red","yellow"},
})

BigWigs:AddSounds("The Lurker Below", {
	["dive"] = {"alarm","alert","info","long"},
	["spout"] = "warning",
})

BigWigs:AddColors("Leotheras the Blind", {
	[37640] = {"red","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["image"] = {"orange","red"},
	["mindcontrol"] = {"blue","orange"},
	["phase"] = {"orange","red","yellow"},
	["whisper"] = {"blue","yellow"},
})

BigWigs:AddSounds("Leotheras the Blind", {
	[37640] = "alert",
	["berserk"] = "alarm",
	["mindcontrol"] = "alert",
})

BigWigs:AddColors("Fathom-Lord Karathress", {
	[38330] = "red",
	["berserk"] = {"orange","red","yellow"},
	["totem"] = {"orange","yellow"},
})

BigWigs:AddSounds("Fathom-Lord Karathress", {
	[38330] = "long",
	["berserk"] = "alarm",
	["totem"] = "alarm",
})

BigWigs:AddColors("Morogrim Tidewalker", {
	[37730] = "orange",
	[37850] = {"blue","red"},
	["globules"] = {"green","red"},
	["murloc"] = {"green","yellow"},
})

BigWigs:AddSounds("Morogrim Tidewalker", {
	[37730] = "alarm",
	[37850] = "alert",
	["globules"] = "alert",
})

BigWigs:AddColors("Lady Vashj", {
	[38280] = {"blue","red"},
	["barrier"] = "yellow",
	["berserk"] = {"orange","red"},
	["elemental"] = "red",
	["naga"] = "yellow",
	["phase"] = {"red","yellow"},
	["strider"] = "yellow",
})

BigWigs:AddSounds("Lady Vashj", {
	[38280] = "alert",
	["berserk"] = "alarm",
	["phase"] = "alarm",
})

BigWigs:AddColors("Doomwalker", {
	[33653] = "orange",
	["earthquake"] = "red",
	["overrun"] = "yellow",
})

BigWigs:AddSounds("Doomwalker", {
	[33653] = "long",
	["earthquake"] = "warning",
	["overrun"] = "alert",
})

BigWigs:AddColors("Gruul the Dragonkiller", {
	[33525] = "orange",
	[33654] = "red",
	[36240] = "blue",
	[36297] = "yellow",
	[36300] = "cyan",
})

BigWigs:AddSounds("Gruul the Dragonkiller", {
	[33525] = "long",
	[33654] = "warning",
	[36240] = "underyou",
	[36297] = "alarm",
	[36300] = "info",
})

BigWigs:AddColors("Doom Lord Kazzak", {
	[21063] = {"blue","yellow"},
	[32960] = "blue",
	[32964] = {"green","orange","red"},
})

BigWigs:AddSounds("Doom Lord Kazzak", {
	[32960] = "warning",
})

BigWigs:AddColors("Magtheridon", {
	[30168] = {"green","red"},
	[30616] = "red",
	[36449] = {"blue","orange"},
	["abyssal"] = "cyan",
	["berserk"] = {"orange","red"},
	["heal"] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Magtheridon", {
	[30168] = "info",
	[30616] = "warning",
	[36449] = {"alert","long"},
	["berserk"] = "alarm",
	["heal"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("High King Maulgar", {
	[33054] = "yellow",
	[33131] = "yellow",
	[33147] = "orange",
	[33152] = "red",
	[33232] = "orange",
	[33238] = "red",
})

BigWigs:AddSounds("High King Maulgar", {
	[33054] = "info",
	[33131] = "alert",
	[33152] = "alarm",
	[33232] = "long",
})

BigWigs:AddColors("Attumen the Huntsman Raid", {
	[29833] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Attumen the Huntsman Raid", {
	[29833] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Hyakiss the Lurker", {
	[29896] = {"blue","orange"},
})

BigWigs:AddSounds("Hyakiss the Lurker", {
})

BigWigs:AddColors("Moroes Raid", {
	[29425] = {"blue","red"},
	[29448] = "orange",
	[37023] = "orange",
	[37066] = {"blue","yellow"},
})

BigWigs:AddSounds("Moroes Raid", {
	[29425] = "warning",
	[29448] = "info",
	[37023] = "long",
	[37066] = "alert",
})

BigWigs:AddColors("Maiden of Virtue Raid", {
	[29511] = "red",
	[29522] = {"blue","yellow"},
})

BigWigs:AddSounds("Maiden of Virtue Raid", {
	[29511] = "warning",
	[29522] = "alert",
})

BigWigs:AddColors("Romulo & Julianne", {
	[30822] = {"blue","yellow"},
	[30878] = "orange",
	["buff"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Romulo & Julianne", {
	[30878] = "warning",
	["buff"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("The Big Bad Wolf", {
	[30753] = {"blue","yellow"},
})

BigWigs:AddSounds("The Big Bad Wolf", {
	[30753] = "warning",
})

BigWigs:AddColors("The Crone", {
	[32337] = "orange",
	["spawns"] = "yellow",
})

BigWigs:AddSounds("The Crone", {
	[32337] = "info",
})

BigWigs:AddColors("The Curator Raid", {
	[30254] = "red",
	[30403] = "orange",
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("The Curator Raid", {
	[30254] = "warning",
	[30403] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Terestian Illhoof", {
	[30065] = {"green","red"},
	[30115] = {"blue","yellow"},
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("Terestian Illhoof", {
	[30065] = {"info","long"},
	[30115] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Shade of Aran", {
	[29951] = {"blue","orange"},
	[29962] = "cyan",
	[29973] = "yellow",
	[30004] = {"blue","red","yellow"},
	["drink"] = {"cyan","orange"},
})

BigWigs:AddSounds("Shade of Aran", {
	[29951] = "underyou",
	[29973] = "info",
	[30004] = {"long","warning"},
})

BigWigs:AddColors("Netherspite", {
	[30466] = {"blue","purple"},
	[37063] = "yellow",
	[38523] = "orange",
	["berserk"] = {"orange","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Netherspite", {
	[30466] = "warning",
	[37063] = "info",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Prince Malchezaar", {
	[30843] = {"blue","red"},
	[30852] = "yellow",
	["infernal"] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Prince Malchezaar", {
	[30843] = "warning",
	[30852] = "alarm",
	["infernal"] = {"alert","info"},
	["stages"] = "long",
})

BigWigs:AddColors("Nightbane Raid", {
	[30129] = "blue",
	[36922] = "red",
	[37098] = "orange",
	["stages"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Nightbane Raid", {
	[30129] = "underyou",
	[36922] = "alert",
	[37098] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Al'ar", {
	[35181] = {"orange","red"},
	[35383] = "blue",
	[35410] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Al'ar", {
	[35181] = "alert",
	[35383] = "alarm",
	[35410] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Void Reaver", {
	[25778] = {"blue","green"},
	[34172] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Void Reaver", {
	[25778] = "alarm",
	[34172] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("High Astromancer Solarian", {
	[42783] = {"blue","yellow"},
	["phase"] = {"green","red"},
	["split"] = "red",
})

BigWigs:AddSounds("High Astromancer Solarian", {
	[42783] = "warning",
})

BigWigs:AddColors("Kael'thas Sunstrider", {
	[37018] = {"blue","yellow"},
	[37027] = {"blue","yellow"},
	[44863] = {"orange","yellow"},
	["gaze"] = {"blue","red"},
	["mc"] = {"blue","red"},
	["phase"] = {"green","red","yellow"},
	["pyro"] = {"green","yellow"},
	["rebirth"] = {"orange","yellow"},
})

BigWigs:AddSounds("Kael'thas Sunstrider", {
	["mc"] = "alert",
})

BigWigs:AddColors("High Warlord Naj'entus", {
	[39837] = {"blue","red"},
	[39872] = {"green","red","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("High Warlord Naj'entus", {
	[39837] = "warning",
	[39872] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Supremus", {
	[40126] = "yellow",
	[40265] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["fixate"] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Supremus", {
	[40265] = "alert",
	["berserk"] = "alarm",
	["fixate"] = "warning",
	["stages"] = "info",
})

BigWigs:AddColors("Shade of Akama", {
	[42023] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Shade of Akama", {
	[42023] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Teron Gorefiend", {
	[40243] = {"blue","orange"},
	[40251] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Teron Gorefiend", {
	[40243] = "alert",
	[40251] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Gurtogg Bloodboil", {
	[40481] = {"blue","green"},
	[40491] = {"blue","green"},
	[40508] = {"blue","red"},
	[40604] = {"blue","cyan","orange"},
	[42005] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Gurtogg Bloodboil", {
	[40481] = "alarm",
	[40491] = "alert",
	[40508] = "alert",
	[40604] = {"info","warning"},
	[42005] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Reliquary of Souls", {
	[41294] = {"blue","red"},
	[41303] = {"blue","yellow"},
	[41305] = {"green","orange"},
	[41376] = {"blue","red"},
	[41410] = "red",
	[41426] = {"blue","yellow"},
	[41431] = "orange",
	["zero_mana"] = "cyan",
})

BigWigs:AddSounds("Reliquary of Souls", {
	[41294] = "warning",
	[41303] = "alert",
	[41305] = "info",
	[41376] = "alert",
	[41410] = "info",
	[41426] = "alarm",
	[41431] = "warning",
})

BigWigs:AddColors("Mother Shahraz", {
	[40880] = "yellow",
	[40882] = "yellow",
	[40883] = "yellow",
	[40891] = "yellow",
	[40896] = "yellow",
	[40897] = "yellow",
	[41001] = {"blue","orange"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Mother Shahraz", {
	[40880] = "info",
	[40882] = "info",
	[40883] = "info",
	[40891] = "info",
	[40896] = "info",
	[40897] = "info",
	[41001] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("The Illidari Council", {
	[41450] = "red",
	[41451] = "red",
	[41453] = {"green","yellow"},
	[41455] = "orange",
	[41475] = {"green","red"},
	[41476] = {"green","yellow"},
	[41481] = "blue",
	[41482] = "blue",
	[41485] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("The Illidari Council", {
	[41450] = "info",
	[41451] = "info",
	[41455] = "warning",
	[41475] = "long",
	[41476] = "alert",
	[41481] = "alarm",
	[41482] = "alarm",
	[41485] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Illidan Stormrage", {
	[39869] = "orange",
	[40018] = {"blue","yellow"},
	[40506] = {"green","red"},
	[40585] = {"blue","red"},
	[40611] = "blue",
	[40683] = "orange",
	[40695] = {"green","red"},
	[40841] = "blue",
	[40932] = {"blue","red"},
	[41032] = {"blue","red"},
	[41117] = "red",
	[41126] = "red",
	[41917] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Illidan Stormrage", {
	[39869] = "warning",
	[40018] = {"alert","info"},
	[40506] = "alarm",
	[40585] = "alert",
	[40611] = "alert",
	[40683] = "long",
	[40695] = {"info","warning"},
	[40841] = "alert",
	[40932] = "alert",
	[41032] = "alert",
	[41117] = "alert",
	[41126] = "alert",
	[41917] = "long",
	["berserk"] = "alarm",
	["stages"] = "alarm",
})

BigWigs:AddColors("Kalecgos", {
	[44799] = "yellow",
	[44806] = {"orange","red"},
	[44866] = "orange",
	[45029] = {"blue","orange"},
	["realm"] = "orange",
	["wild_magic_casting"] = {"green","yellow"},
	["wild_magic_healing"] = "yellow",
	["wild_magic_hit"] = {"blue","yellow"},
	["wild_magic_threat"] = "blue",
})

BigWigs:AddSounds("Kalecgos", {
	[44799] = "info",
	[44806] = "alarm",
	[44866] = "alert",
	["realm"] = "alert",
	["wild_magic_casting"] = "long",
	["wild_magic_healing"] = "long",
	["wild_magic_hit"] = "long",
})

BigWigs:AddColors("Brutallus", {
	[45150] = "orange",
	[45185] = {"blue","orange","yellow"},
	[46394] = {"blue","green","red","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["burnresist"] = "green",
})

BigWigs:AddSounds("Brutallus", {
	[45150] = "alert",
	[46394] = {"info","warning"},
	["berserk"] = "alarm",
})

BigWigs:AddColors("Felmyst", {
	[45402] = {"blue","orange"},
	[45661] = {"blue","red","yellow"},
	[45855] = "yellow",
	[45866] = {"blue","purple"},
	["berserk"] = {"orange","red","yellow"},
	["breath"] = "yellow",
	["phase"] = "yellow",
})

BigWigs:AddSounds("Felmyst", {
	[45402] = "alert",
	[45661] = "alert",
	[45866] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("The Eredar Twins", {
	[45230] = {"blue","green","orange"},
	[45329] = {"blue","red"},
	[45342] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("The Eredar Twins", {
	[45230] = "info",
	[45329] = "long",
	[45342] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("M'uru", {
	[45934] = "red",
	[45996] = "orange",
	[46282] = "orange",
	["berserk"] = {"orange","red","yellow"},
	["humanoid"] = "orange",
	["sentinel"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("M'uru", {
	[45996] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Kil'jaeden", {
	[45641] = {"blue","red"},
	[45848] = "orange",
	[45885] = "yellow",
	[45892] = "yellow",
	[46605] = {"orange","yellow"},
	["blueorb"] = "yellow",
	["orb"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Kil'jaeden", {
	[45641] = "warning",
	[45848] = "info",
	[46605] = "long",
	["orb"] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Akil'zon", {
	[43648] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Akil'zon", {
	[43648] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Nalorakk", {
	[42398] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "red",
})

BigWigs:AddSounds("Nalorakk", {
	[42398] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Jan'alai", {
	[42630] = "orange",
	[43140] = {"blue","red"},
	[43962] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Jan'alai", {
	[42630] = "info",
	[43140] = "alert",
	[43962] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Halazzi", {
	[43139] = "red",
	[43302] = "orange",
	[43303] = {"blue","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("Halazzi", {
	[43302] = "alert",
	[43303] = "alarm",
})

BigWigs:AddColors("Hex Lord Malacrass", {
	[43383] = "red",
	[43421] = {"blue","orange"},
	[43429] = "red",
	[43431] = "orange",
	[43436] = "yellow",
	[43451] = "orange",
	[43501] = {"blue","yellow"},
	[43548] = "orange",
})

BigWigs:AddSounds("Hex Lord Malacrass", {
	[43421] = "alarm",
	[43429] = "info",
	[43431] = "alarm",
	[43436] = "alert",
	[43451] = "alarm",
	[43548] = "alarm",
})

BigWigs:AddColors("Zul'jin", {
	[43093] = {"blue","yellow"},
	[43095] = "yellow",
	[43150] = {"blue","red"},
	["stages"] = "red",
})

BigWigs:AddSounds("Zul'jin", {
	[43093] = "alarm",
	[43095] = "warning",
	[43150] = "alert",
})
