sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "J27By4HftLdwoeyj/ig+/EUTAmJKsSCroaVnaJFusHpdqpL78nN5P7MhpbJW7kdjzfNcnwAshw52HwZ51ycQInS0JwSLuZb+vAyb5WDFxBO8B7DU001oSqoHphINrJ07jEs2c12eWxcQ5Ta6iOn2FDRqLJjr5lSXQ1TGZMZ0E3GFKiLVJWL2Scfe1OuG6HfAsaDJ2rkY4VpmN8Kf2Dx7FvptFQZy6pTrnOhiQJQ9CUlRgtbhl2nNB340dEqCgT36hi7gEWhSZ43Z0Nvn4ZIfpyX//3RG50laTp/ShnurW4kkUk4ZNw1mlT6mrZ4w7apDqF6OGRBhFR6IRSXFN/yGA+3fzDo4L3aLY3MS02uQlvkOyUUkqA3KQJ6q/kiALAq8edsjXRShfsvf+SEOLWZLSx/vkUKjINQtaskn+vyR8EfwNyGvuK0ew7OmjHdpqpOopH98i0rKH8otqd+pOWtkr2UR44NTPxpfK8ThAlVL4ksa/hSJjACM/8DxKKMyHIa2NBHNOTRLU4xZPSEFlmBdLSCAdYevXuYORUfP6RxszLynzbWhoe+HsNhoDCAXF3AQKwlzR4K59YTx36maAivtnKQXCVKWHX+7VRjucIg2HyA60c4K/TKvyEnyWAjHSTVlSJJwOhmxajrpKYKpvljM+5NGkJghqSLChpm+ZtC2cLU="
  - secure: "pgaP33c24lMKhcutTTZyJVnplMLcaRbC9IgKwH/DzCFaBfWvC28/4jzn3xtjEvsdYsUXdAFYDXa5EIyG5UmNjGp7xmINSrmEs/fEZYLR/JqEa4yww+PBwjpBfE4og3MuRJ4MnLtDzddHEH4cM97mRUwBi50XGYRtLhjDvkFc1WPRaBAradVshd4Z3+F7ytwGR1E+HX7w5A0T0Q/dLQ07tXeKCqNkeoyi1uXEJKsk1NicC9bJAGwp6M8ne6osesOzAUQVSQPXak9LQAMYWZqzatEGU8906EEzZJGq8ia3Htitmd7ZAmxgaZZeV2aWz1dElA5bo5dfgbsEWDhiTz3FlWd8EAdI9/fiF9UyZfjO0ePE2dvAngd9fsfVq7UmIvrOu66fZB9o5GOk0vYziCp57zKm5Md2IihCxJfXe4vsAnpP2/SoMi6qEu5J7IWDqJaE+pMKz1kSvcNxScpiqV33FBqyD5shccHYPiQlmExa3CCIaV7IE4kdmiNDjiWFT5TumNrw0k6C5obojesAts+7++S9RrDWemEhk8FXl3e8uTH8YaHxC7jFiYNgknSmvH74/Nt563+wloejXgRVu99xbrf6g7wtvnLhQrLwB8hi4KV8RHiv+1Y9QRNToDyAgZcs0VaWVBLtoUjFbbS8pf5ObKGQxJcOMkhIm3RmX8dMgpo="
  - secure: "TPkGVhEofyW+8IaA2f0/aOTOytE+x+kB0uiQpdbbDH2i54aSynQxlMDzxvQ3nKE+Vk8xsbqRqfRC+8f5mKNra1W2GGjo9IdZZH17sGBpzxlirP+y0p83MrvKHNFmH61UxR0humvMqfM6CrfIjrLpbdJRINThH1ICDtJY+XGCV+oaB3ftYd984Un/TGQiSL7etwzv32V2dLw8nrT6Itpkptq4Rp6YSfzJSxaminLRDCvorj/7RQD4p6D22TrDEciZSEs+ms3t0jp743W8eKukGwmTKiLb911qKhbI42eATT0+7gP4LJACyuhZM9YvQNViGngpR6AxEg0blnTSwMwV+XvogKMwax+pQYn5tYG2Do3VkISn4ZjrDCk0vCyCh2UF3kgrrW0OAQVTMDD6Qi8pgmcHmDyCCAJOMc8Sklk2IuHKo9n05ZbnglxLG0KF5u+rQNS0KXLjA+yx4Tb4RCiWSB9bDQR3xUVhFFOl77QhScePq4xBFWbXCR8B4AYmECwhevboZkiIIe+e7cIY0BfgIMWR4zZWKk+6b7iaXrlKQwGLQqxfyFI8uxce9g5TNjcnX9FGZaAt/HVqgy6HBStu7a8z8bGkVvbI0CZlMivxLJ10npzp9Y2gLasHeO1md5zKO9zp2UacRYhfmwm2X95tFVvqQtzS2hZgUjsbNHJXJTA="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
