-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Doomwalker", {
	[33653] = "orange",
	["earthquake"] = "red",
	["overrun"] = "yellow",
})

BigWigs:AddSounds("Doomwalker", {
	[33653] = "long",
	["earthquake"] = "warning",
	["overrun"] = "alert",
})

BigWigs:AddColors("Gruul the Dragonkiller", {
	[33525] = "orange",
	[33654] = "red",
	[36240] = "blue",
	[36297] = "yellow",
	[36300] = "cyan",
})

BigWigs:AddSounds("Gruul the Dragonkiller", {
	[33525] = "long",
	[33654] = "warning",
	[36240] = "underyou",
	[36297] = "alarm",
	[36300] = "info",
})

BigWigs:AddColors("Doom Lord Kazzak", {
	[21063] = {"blue","yellow"},
	[32960] = "blue",
	[32964] = {"green","orange","red"},
})

BigWigs:AddSounds("Doom Lord Kazzak", {
	[32960] = "warning",
})

BigWigs:AddColors("Magtheridon", {
	[30616] = "red",
	[36449] = {"blue","orange"},
	["abyssal"] = "cyan",
	["banish"] = {"green","red"},
	["escape"] = "yellow",
	["heal"] = "orange",
})

BigWigs:AddSounds("Magtheridon", {
	[30616] = "warning",
	[36449] = {"alert","long"},
	["banish"] = "info",
	["heal"] = "alarm",
})

BigWigs:AddColors("High King Maulgar", {
	[33054] = "yellow",
	[33131] = "yellow",
	[33147] = "orange",
	[33152] = "red",
	[33232] = "orange",
	[33238] = "red",
})

BigWigs:AddSounds("High King Maulgar", {
	[33054] = "info",
	[33131] = "alert",
	[33152] = "alarm",
	[33232] = "long",
})
